Add reviews link to footer and footer spec
sharesight/www.sharesight.com pull request #202
Opened 2020-09-03 20:26 UTC by irwalker

[vimaly](https://vimaly.com/#j8mqm/t/www_Add_Reviews_link_to_footer/Xc1vCD2gUb4AYNzCY)

2020-09-03 20:41 UTC, CitationNerded approved these changes
Nice one - looks just like my attempt did but i couldnt get the app running to verify

2020-09-03 21:29 UTC, kylorhall requested changes
Yes, but not quite (I think).  You can see what it is on staging though.

2020-09-03 21:29 UTC, kylorhall commented on spec/features/footer_spec.rb
> +describe 'Footer', type: :feature do
👍

2020-09-03 21:29 UTC, kylorhall commented on source/partials/_site_footer.html.erb
> +        <a href="<%= localize_url('reviews', locale_id: locale_obj[:id]) %>" class="footer__link" title="<%= locale_page(page: 'reviews')[:page_title] %>">
I don't believe we will have a `locale_page(page: 'reviews')[:page_title]`.  This likely needs its own title.

2020-09-03 22:30 UTC, kylorhall approved these changes
See what happens~!

2020-09-09 01:40 UTC, irwalker commented
Getting this to work on mobile was weirdly hard. If you add or take anything away from the list, the layout no longer works on smaller screens.

Sam and I reformatted the list so it looks better on mobile, and OK on desktop. What are your thoughts pls @kylorhall ? Other option is to rebuild these elements using a table or something because the `li` way its done is a 'mare

Desktop
![image](https://user-images.githubusercontent.com/2808271/92544403-f8707f00-f2a1-11ea-8a06-8e20987fcf32.png)

Tablet
![image](https://user-images.githubusercontent.com/2808271/92544413-fdcdc980-f2a1-11ea-8637-a3fdb98d091b.png)

Mobile
![image](https://user-images.githubusercontent.com/2808271/92544420-032b1400-f2a2-11ea-9de4-1f38ccd1fa8d.png)

2020-09-10 21:15 UTC, merged