Removing references to rss feed
sharesight/www.sharesight.com pull request #368
Opened 2022-03-22 03:30 UTC by maisiembleton

2022-03-28 01:51 UTC, kylorhall requested changes
Removing the file LGTM…but I'm not sure sure about removing the `<link>` itself..

2022-03-28 01:51 UTC, kylorhall commented on source/layouts/partials/_meta.html.erb
> -<link rel="alternate" type="application/rss+xml" title="Sharesight RSS Feed" href="<%= base_url('/blog/feed.xml') %>">
I think you still need to link to this, even though the link no longer exists here…it exists in Gatsby.

2022-03-28 01:51 UTC, kylorhall commented on spec/features/blog_categories_page_spec.rb
> -        expect(page).to have_head('link', args: { rel: 'alternate', href: base_url('blog/feed.xml') }, debug: :href)
Restore this if you restore the link.

2022-03-28 01:51 UTC, kylorhall commented on spec/features/blog_posts_page_spec.rb
> -      expect(page).to have_head('link', args: { rel: 'alternate', href: base_url('blog/feed.xml') }, debug: :href)
Restore this if you restore the link.

2022-03-28 01:51 UTC, kylorhall commented on spec/features/landing_pages_page_spec.rb
> -    expect(page).to have_head('link', args: { rel: 'alternate', href: base_url('blog/feed.xml') }, debug: :href)
Restore this if you restore the link.

2022-03-28 02:17 UTC, maisiembleton commented
Does that mean there's actually no changes to middleman for this page? @kylorhall

2022-03-28 05:36 UTC, kylorhall commented
> Does that mean there's actually no changes to middleman for this page? @kylorhall

You should still delete the builder itself; Middleman shouldn't build this page anymore, but it still needs to link to it.

2022-03-30 00:40 UTC, kylorhall approved these changes
Looks fine…I'll just note all of your files aside from `source/blog/feed.xml.builder` are just whitespace changes—it's a bit weird 😛

Your IDE probably needs fixes if it's saving whitespace arbitrarily.

2022-03-30 03:35 UTC, merged